### ISSUE TITLE
Is the inline documentation correct for kwarg time?

### ISSUE THREAD

**Issue by stevenou** [klaviyo/ruby-klaviyo#24]
https://github.com/klaviyo/ruby-klaviyo/blob/90d6065b5e8d631062b893a01ead62bcd5e7f5d4/lib/klaviyo/apis/public.rb#L41

I don't think `time` is supposed to be an integer based on the code here which calls `to_time.to_i` https://github.com/klaviyo/ruby-klaviyo/blob/90d6065b5e8d631062b893a01ead62bcd5e7f5d4/lib/klaviyo/apis/public.rb#L69

**Comment by remstone7** [comment]
looks like you're correct, the unix timestamp should be the argument, not a datetime

**Comment by cpcurtis1218** [comment]
Corrected in v2.0.6
