### ISSUE TITLE
2.0.5 breaking change

### ISSUE THREAD

**Issue by stevenou** [klaviyo/ruby-klaviyo#28]
Just FYI, 2.0.5 broke for me because the `track` API previously accepted a `Hash` for the `kwargs` but now requires actual keyword arguments (due to changes in `request`). Not sure if this should be considered a major version change as a result?

**Comment by stevenou** [comment]
Actually, it appears it's not just the interface that's broken. The actual method `track` has been broken. I suspect `track` is not the only method affected, based on the diff which changes `request`, `v2_request` and `v1_request` but not any of the methods calling them.

**Comment by stevenou** [comment]
Ok, so my guess is that you guys are on ruby <= 2.7 and I'm on ruby 3.0.0 and the problem stems from https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

In ruby 3, you can no longer pass a `Hash` where keyword arguments are required, but you can in ruby 2. It's deprecated as of ruby 2.7 though. 

So here https://github.com/klaviyo/ruby-klaviyo/blob/429d1c72c7b973e23034eae1543641f821457370/lib/klaviyo/apis/public.rb#L71 it should probably be:
```
public_request(HTTP_GET, 'track', **params)
```
to ensure compatibility with ruby 3.

**Comment by cpcurtis1218** [comment]
Thank you for the details @stevenou I'm working on an update for this now

**Comment by cpcurtis1218** [comment]
This was updated and released in v2.0.6

**Comment by stevenou** [comment]
@cpcurtis1218 thanks for the update - however, to be clear, I believe _every method_ that calls `request` or `public_request` is affected by this, not just `track`. I can confirm, for example, that `create_list` and `get_lists` are definitely affected.
