### ISSUE TITLE
Klaviyo client not thread-safe

### ISSUE THREAD

**Issue by jeffse** [klaviyo/ruby-klaviyo#32]
I have a client with two separate subscriptions to Klaviyo. We'd like to be able to use this Ruby library to send events for both subscriptions, each of which has a separate api key.

v1.0 of the ruby-klaviyo library was thread-safe, since I could instantiate the Klaviyo::Client with the api key and make the subsequent requests based on that. v2.0 breaks that thread-safety, since it's a singleton assignment and assumes all requests are going to use the same api key.

Will there be a way going forward to specify api keys for particular requests?

**Comment by smoucka** [comment]
Hi @jeffse. Yes, we can include the ability to configure a different api key on a per-request basis in a future release.

**Comment by jeffse** [comment]
That would be fantastic. For the moment, I'm just sticking to v1.0, which does what I need so far.

**Comment by jonathanpa** [comment]
> That would be fantastic. For the moment, I'm just sticking to v1.0, which does what I need so far.

Same for me. Waiting support of several concurrent keys to migrate to the new version.

**Comment by popcorn** [comment]
@jeffse @smoucka - I'm also looking into using this gem for multiple API keys from the same app, which v1.0 supports.

Do I lose any functionality if I decide to use v1.0 instead of v2.0 of this gem?

**Comment by smoucka** [comment]
@popcorn v1.0 only supports the track/identify endpoints. If that's all you need then you won't lose any functionality.

**Comment by gagandeepsinghj** [comment]
@jeffse @smoucka  I'm also looking into using this gem for multiple API keys from the same app. Any ETA on this one?

**Comment by cpcurtis1218** [comment]
The ruby SDK is now thread-safe as of v2.2.0
