### ISSUE TITLE
Problem with request_profile_deletion

### ISSUE THREAD

**Issue by ciaranc78** [klaviyo/ruby-klaviyo#33]
Hi, I'm trying to delete profiles as follows:

Klaviyo::DataPrivacy.request_profile_deletion('email', 'newuser2@klaviyo.com')

but I'm getting the following ArgumentError:

ArgumentError (wrong number of arguments (given 3, expected 2))

am I missing something here? I've tried it with profile_id & phone_number with the same result

**Comment by cpcurtis1218** [comment]
I'm working on an update for this now and should be released by the end of this week

**Comment by cpcurtis1218** [comment]
This is fixed in v2.0.8, closing this issue now

**Comment by ciaranc78** [comment]
Great, thanks a million for that & sorry for the late reply....lambing season in Donegal!
