### ISSUE TITLE
Hard Yank Causing Web App Deploy Failure...

### ISSUE THREAD

**Issue by jakemumu** [klaviyo/ruby-klaviyo#43]
I just went to deploy my web app to production and all old versions of the Klaviyo gem were yanked? 

What the heck guys...

**Comment by synim-sogody** [comment]
Is there any update on this issue? In case we have to update to v2.0.9, are there any breaking changes that we need to worry about?

**Comment by clarkdave** [comment]
Any update on this? v2 has a significant breaking change from v1 in that [it's not thread safe](https://github.com/klaviyo/ruby-klaviyo/issues/32) like v1 was.

**Comment by createmycookbook** [comment]
Why did you hard yank?

**Comment by jakemumu** [comment]
Thank you!
