### ISSUE TITLE
How can I send the email?

### ISSUE THREAD

**Issue by remy727** [klaviyo/ruby-klaviyo#52]
I saw this still uses `https://a.klaviyo.com/api/v1/email-template/{template_id}/send` which was deprecated.
```
# send template
Klaviyo::EmailTemplates.send_template(
  'TEMPLATE_ID',
  from_email: 'FROM_EMAIL_ADDRESS',
  from_name: 'FROM_EMAIL_NAME',
  subject: 'EMAIL_SUBJECT',
  to: 'RECIPIENT_EMAIL_ADDRESS',
  context: {
    name: 'RECIPIENT_NAME',
    email: 'RECIPIENT_EMAIL_ADDRESS'
  }
)
```

What is the solution to send Klaviyo email using the API?

**Comment by mangoceylon** [comment]
We are working on a new version of this SDK which will have this endpoint included, for now you would need to create a method using the endpoint described here: https://developers.klaviyo.com/en/reference/create-campaign.
