### ISSUE TITLE
Remove middleware install requirement

### ISSUE THREAD

**Issue by sjf125** [klaviyo/ruby-klaviyo#6]
THe following line is no longer needed, since using rack:

`config.middleware.use "Klaviyo::Client::Middleware", "YOUR_KLAVIYO_API_TOKEN"`

**Comment by jonathanpa** [comment]
@sjf125 So where and how do you setup the api token ?

**Comment by arslanaly47** [comment]
@sjf125 Same question as from @jonathanpa. I'm not sure where to add the API token then.

**Comment by cpcurtis1218** [comment]
Closing this issue as it will be handled in an upcoming PR
